server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    enabled: true
    multipart:
      max-file-size: 512MB
      file-size-threshold: 1MB
      max-request-size: 512MB
  datasource:
    url: jdbc:mysql://192.168.0.99:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#  data:
#    mongodb:
#      uri: mongodb://ceshi:123456@192.168.1.15:27017/ceshi

  redis:
    flush-mode: immediate
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active:  10
        max-idle: 8
        max-wait: -1ms
        timeout: 10000ms

#mybatis
mybatis:
  type-aliases-package: com.example.demo.entity
  #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  #分页合理化
  reasonable: true
  #是否支持接口参数来传递分页参数，默认false
  supportMethodsArguments: true
  #当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
  pageSizeZero: true
  params: count=countSql
  #RowBounds参数offset作为PageNum使用 - 默认不使用
  offsetAsPageNum: true
  #RowBounds是否进行count查询 - 默认不查询
  rowBoundsWithCount: true
  returnPageInfo: true
